# spring-数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///student_grade_manage?useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
# mybatis配置
mapper:
  identity: MYSQL
  not-empty: true
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.MySqlMapper
# 配置日记
logging:
  level:
    com.gx.pagehelperdemo.mapper: debug
  file: D:/logs/pagehelper-demo/debug.log
# 分页插件
pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql